### ISSUE TITLE
skull length

### ISSUE THREAD

**Issue by megbalk** [futres/fovt#103]
make parent term skull length
make children terms: skull dorsal length, condylobasal length and basal length 

condylobasal length and basal length will have broad synonym skull ventral length

**Comment by megbalk** [comment]
only skull length will have axiom: length and ('characteristic of' some skull)
skull length rdfs:comment: This is measured AP

all the other terms will have "skull length" as subclassof, no axioms

**Comment by megbalk** [comment]
for skull dorsal length in pig:
rdfs:comment: In pigs, the dorsalmost point, the Opisthokranion, is projected into space.

**Comment by helenamachado** [comment]
change 'inheres in' to 'characteristic of'

run reasoner

**Comment by megbalk** [comment]
fixed RO:0000052
