### ISSUE TITLE
temporal crest

### ISSUE THREAD

**Issue by helenamachado** [futres/fovt#118]
Def.: A dorsally concave laterally directed crest that terminated on the caudo-dorsal process of the zygomatic bone. 
 
https://www.researchgate.net/publication/325258124_Morphological_Study_on_the_Skull_of_Wild_Boar_of_Mizoram_Sus_scrofa 

see issue #116

**Comment by megbalk** [comment]
@helenamachado would this have EQ: crest and part of some temporal bone?

**Comment by helenamachado** [comment]
> @helenamachado would this have EQ: crest and part of some temporal bone?

I think so! it may get to the parietal and occipital bones too, so I'll check later!

**Comment by helenamachado** [comment]
I've been looking at some skulls and and some of the definitions and I think we might want to change this definition.

For what I understood, the temporal crest is the nuchal end of the temporal lines and the lateral end of the nuchal crest, by the occipital and temporal bones.

https://www.researchgate.net/figure/Dorsal-view-of-the-Skull-of-Short-Head-Wild-Pig-of-Mizoram-showing-Nuchal-crest-A_fig1_325258124 
Fig 1 (dorsal view) temporal line (c) meets nuchal crest (a) and continues to the temporal crest (d)

https://en.wikipedia.org/wiki/Nuchal_lines

I took a photo of a horse skull and marked the lines/crest for visualization: red is the temporal line, blue is the nuchal line and green is the temporal crest.
![Inkedhorse skull back temporal line temporal crest nuchal crest](https://user-images.githubusercontent.com/77077324/233170313-3ffe1dd9-2971-4fe0-bbf8-25ea7187ee24.jpg)

So in horses the nuchal end of the temporal line turns into the sagittal crest; then the nuchal end of the sagittal crest forms the nuchal crest and then the lateral end of the nuchal crest starts the temporal crest.

In other mammals seems like the temporal crest starts at the junction of the temporal lines with the nuchal crest.
I got this image of the occiput of a blackbuck and I also marked red for the temporal line, blue for the nuchal line and green for the temporal crest.
![Inkednuchal temporal crest line](https://user-images.githubusercontent.com/77077324/233200410-bc776737-32f1-4b4a-a2f9-39ba3ae081fd.jpg)


I was thinking we could make the two terms something like:

**temporal line**
def.: line (or either of two nearly parallel lines) dorsally concave laterally directed that runs upward and backward from the zygomatic arch. It bounds the anterodorsal part of the temporal fossa and its the attachment site to the temporalis muscle.

ref.: https://www.merriam-webster.com/medical/temporal%20line
https://www.imaios.com/en/e-anatomy/anatomical-structure/temporal-line-1536895640
https://en.wikipedia.org/wiki/Parietal_bone

EQ: anatomical line and part of some frontal bone and part of some parietal bone


**temporal crest**
def.: A ridge or similar projection connected to the temporal lines and nuchal crest on the squamous part of the occipital bone. It bounds the posteroventral part of the temporal fossa.

ref.: https://www.researchgate.net/publication/325258124_Morphological_Study_on_the_Skull_of_Wild_Boar_of_Mizoram_Sus_scrofa

EQ: crest and part of some temporal bone and part of some occipital bone

**Comment by megbalk** [comment]
make an issue on uberon with the suggested changes and comments, then create a branch, make the changes, then make a PR for review!

**Comment by helenamachado** [comment]
will do!

Just checked and there's a temporal crest issue that is closed (https://github.com/obophenotype/uberon/issues/2775). Do you know how should I move on from there?

**Comment by megbalk** [comment]
you can create a new issue about this and create a new branch for that issue.
