### ISSUE TITLE
phalanges

### ISSUE THREAD

**Issue by megbalk** [futres/fovt#139]
may skip other species that aren't horses because VDD does not state which digit the phalanx is for. @helenamachado can you help me figure it out?

**Comment by megbalk** [comment]
what is the lateral second phalanx?

**Comment by megbalk** [comment]
skipping M7 as it is an angle and not a linear measurement

**Comment by helenamachado** [comment]
> 

Phalanges varies in shape between proximal (1st), medial (2nd) and distal (3rd) phalanges, but not really between digits. For instance, is easier to identify a deer proximal phalanx, but not as much if it's from digit 3 or 4. So all measurements for proximal phalanx could be used in the proximal phalanges of all the digits.

I'm pretty sure that goes for all the weight-baring digits. 
I know pigs digits 2&5 and that first digit of cats and dogs are slightly different, but I think the measurements are still the same even in those. I'll check in our collections next week and I'll get back to you!

**Comment by megbalk** [comment]
@helenamachado thanks! So should I make phalanges measurements for all (1-5)?

**Comment by helenamachado** [comment]
yes :)

**Comment by megbalk** [comment]
also not adding taxon restrictions
