### ISSUE TITLE
Unasserted inferred equivalences

### ISSUE THREAD

**Issue by gouttegd** [futres/fovt#146]
The FOVT ontology currently contains a handful of classes that are inferred to be equivalent to each other, even though they are not explicitly asserted as such. This is not allowed by default in the ODK configuration (which calls ROBOT’s `reason` command with `--equivalent-classes-allowed asserted-only`), as such inferred equivalences are typically indicative of problematic logical definitions – which indeed seems to be the case here.

Here are the affected classes:

### [humerus proximal breadth](http://purl.obolibrary.org/obo/FOVT_0001035) inferred to be equivalent to [radius proximal breadth](http://purl.obolibrary.org/obo/FOVT_0001129)

Both classes have the same logical definition:

> [width](http://purl.obolibrary.org/obo/PATO_0000921) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some '[proximal epiphysis of humerus](http://purl.obolibrary.org/obo/UBERON_0004411)')

Most likely the correct logical definition for [radius proximal breadth](http://purl.obolibrary.org/obo/FOVT_0001129) should be

> [width](http://purl.obolibrary.org/obo/PATO_0000921) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some '[proximal epiphysis of radius](http://purl.obolibrary.org/obo/UBERON_0004413)')

### [upper secondary premolar tooth 3 occlusal surface length](http://purl.obolibrary.org/obo/FOVT_0001252) inferred to be equivalent to [upper secondary canine tooth to premolar tooth 3 length](http://purl.obolibrary.org/obo/FOVT_0001344)

Both classes have the same logical definition:

> [length](http://purl.obolibrary.org/obo/PATO_0000122) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some ('[premolar 3](http://purl.obolibrary.org/obo/UBERON_7500056)' and ('[part of](http://purl.obolibrary.org/obo/RO_0000050)' some '[upper jaw region](http://purl.obolibrary.org/obo/UBERON_0001709)') and ('[part of](http://purl.obolibrary.org/obo/RO_0000050)' some '[secondary dentition](http://purl.obolibrary.org/obo/UBERON_0007774)')))

Not sure which definition is incorrect here, and what the correct definition would be…

### [fused metatarsal bones 3 and 4 length](http://purl.obolibrary.org/obo/FOVT_0001140) inferred to be equivalent to [fused metapodial bones 3 and 4 length](http://purl.obolibrary.org/obo/FOVT_0001143)

Both classes have the same logical definition:

> [length](http://purl.obolibrary.org/obo/PATO_0000122) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some '[fused metacarpal bones 3 and 4](http://purl.obolibrary.org/obo/UBERON_0013587)')

I suppose both logical definitions are actually incorrect. Most likely the correct logical definition for [fused metapodial bones 3 and 4 length](http://purl.obolibrary.org/obo/FOVT_0001143) should be

> [length](http://purl.obolibrary.org/obo/PATO_0000122) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some '[fused metapodial bones 3 and 4](http://purl.obolibrary.org/obo/UBERON_0013586)')

and the correct logical definition for [fused metatarsal bones 3 and 4 length](http://purl.obolibrary.org/obo/FOVT_0001140) should be

> [length](http://purl.obolibrary.org/obo/PATO_0000122) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some '[fused metatarsal bones 3 and 4](http://purl.obolibrary.org/obo/UBERON_0013588)')

### [premolar tooth 4 occlusal surface length](http://purl.obolibrary.org/obo/FOVT_0001263) inferred to be equivalent to [premolar tooth 5 occlusal surface length](http://purl.obolibrary.org/obo/FOVT_0001277)

Both classes have the same logical definition:

> [length](http://purl.obolibrary.org/obo/PATO_0000122) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some '[premolar tooth 5](http://purl.obolibrary.org/obo/UBERON_0018646)'

Most likely the correct logical definition for [premolar tooth 4 occlusal surface length](http://purl.obolibrary.org/obo/FOVT_0001263) should be

> [length](http://purl.obolibrary.org/obo/PATO_0000122) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some '[premolar tooth 4](http://purl.obolibrary.org/obo/UBERON_0018647)'

### [upper premolar tooth 5 occlusal surface length](http://purl.obolibrary.org/obo/FOVT_0001278) inferred to be equivalent to [upper premolar tooth 5 occlusal surface length](http://purl.obolibrary.org/obo/FOVT_0001264)

This is caused by the previous inferred equivalence.

### [lower premolar tooth 4 occlusal surface length](http://purl.obolibrary.org/obo/FOVT_0001265) inferred to be equivalent to [lower premolar tooth 5 occlusal surface length](http://purl.obolibrary.org/obo/FOVT_0001279)

Likewise.

### [proximal phalanx of pedial digit 2 proximal breadth](http://purl.obolibrary.org/obo/FOVT_0001856) inferred to be equivalent to [proximal phalanx of pedial digit 1 proximal breadth](http://purl.obolibrary.org/obo/FOVT_0001839)

Both classes have the same logical definition:

> [width](http://purl.obolibrary.org/obo/PATO_0000921) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some '[proximal phalanx of pedal digit 1](http://purl.obolibrary.org/obo/UBERON_0004332)')

Most likely the correct logical definition for [proximal phalanx of pedial digit 2 proximal breadth](http://purl.obolibrary.org/obo/FOVT_0001856) should be

> [width](http://purl.obolibrary.org/obo/PATO_0000921) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some '[proximal phalanx of pedal digit 2](http://purl.obolibrary.org/obo/UBERON_0004333)')

### [distal phalanx of manual digit 3 proximal depth](http://purl.obolibrary.org/obo/FOVT_0001728) inferred to be equivalent to [distal phalanx of manual digit 4 proximal depth](http://purl.obolibrary.org/obo/FOVT_0001806)

Both classes have the same logical definition:

> [depth](http://purl.obolibrary.org/obo/PATO_0001595) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some ('[in proximal side of](http://purl.obolibrary.org/obo/BSPO_0000124)' some '[distal phalanx of manual digit 3](http://purl.obolibrary.org/obo/UBERON_0004312)'))

Most likely the correct logical definition for [distal phalanx of manual digit 4 proximal depth](http://purl.obolibrary.org/obo/FOVT_0001806) should be

> [depth](http://purl.obolibrary.org/obo/PATO_0001595) and ('[characteristic of](http://purl.obolibrary.org/obo/RO_0000052)' some ('[in proximal side of](http://purl.obolibrary.org/obo/BSPO_0000124)' some '[distal phalanx of manual digit 4](http://purl.obolibrary.org/obo/UBERON_0004313)'))

**Comment by megbalk** [comment]
see latest commit [7f4527d](https://github.com/futres/fovt/commit/7f4527d6188a1933bbe73a87729cf671f3d24f4b)
