### ISSUE TITLE
FOVT using some wrong/ideosyncratic PURLs

### ISSUE THREAD

**Issue by matentzn** [futres/fovt#20]
https://purl.obolibrary.org/obo/FOVT_0000001
https://purl.obolibrary.org/obo/FOVT_0000002
https://purl.obolibrary.org/obo/FOVT_0000003
https://purl.obolibrary.org/obo/FOVT_0000004
https://purl.obolibrary.org/obo/FOVT_0000005
https://purl.obolibrary.org/obo/FOVT_0000006
https://purl.obolibrary.org/obo/FOVT_0000007
https://purl.obolibrary.org/obo/FOVT_0000008
https://purl.obolibrary.org/obo/FOVT_0000009
https://purl.obolibrary.org/obo/FOVT_0000010
https://purl.obolibrary.org/obo/FOVT_0000012
https://purl.obolibrary.org/obo/FOVT_0000013
https://purl.obolibrary.org/obo/FOVT_0000014
https://purl.obolibrary.org/obo/FOVT_0000015
https://purl.obolibrary.org/obo/FOVT_0000016
https://purl.obolibrary.org/obo/FOVT_0000017
https://purl.obolibrary.org/obo/FOVT_0000018
https://purl.obolibrary.org/obo/FOVT_0000020
https://purl.obolibrary.org/obo/FOVT_0000021
https://purl.obolibrary.org/obo/FOVT_0000022
https://purl.obolibrary.org/obo/FOVT_0000023
https://purl.obolibrary.org/obo/FOVT_0000025
https://purl.obolibrary.org/obo/FOVT_0000026
https://purl.obolibrary.org/obo/FOVT_0000027
https://purl.obolibrary.org/obo/FOVT_0000028
https://purl.obolibrary.org/obo/FOVT_0000029
https://purl.obolibrary.org/obo/FOVT_0000030
https://purl.obolibrary.org/obo/FOVT_0000032

An example of a correct IRI is (no https!):
http://purl.obolibrary.org/obo/ENVO_01000549

Context:
https://github.com/orgs/OBOFoundry/projects/5

**Comment by megbalk** [comment]
Thank you for catching! fixed!
