### ISSUE TITLE
OBA_VT terms

### ISSUE THREAD

**Issue by megbalk** [futres/fovt#4]
we need to fix the terms that have these IDs and either remove them, find synonyms, and/or re-create them.

**Comment by lbrensk** [comment]
I'm not sure I know what this means. Can you clarify?

**Comment by megbalk** [comment]
Sorry, I meant the OBA_VT terms

**Comment by ramonawalls** [comment]
If the terms have an OBA-VT IRI, then they have logical definitions and we can reuse them as is. Only terms that just have a VT IRI are problematic.
