### ISSUE TITLE
minimal breadth of choana

### ISSUE THREAD

**Issue by helenamachado** [futres/fovt#65]
For new term requests, please provide the following information:

## Preferred term label

minimal breadth of choana

## Parts of the term

1. anatomical feature: posterior nasal aperture
2. points on feature or axis of measurement: left-right axis in posterior size of posterior nasal aperture 
3. type of measurement: width

## Textual definition

The length of the posterior portion of a posterior nasal aperture of the internal naris (choana) along left right axis.

## Suggested parent term

'width' and ('inheres in' some 'in posterior side of' some 'posterior nasal aperture')

'anatomical line' and ('follows_axis' some 'left-right axis') and ('inheres in' some 'in posterior side of' some 'posterior nasal aperture')

## Reference
ISBN: 9004086161, 9789004086166

## Attribution

https://orcid.org/
0000-0001-8415-4848

**Comment by megbalk** [comment]
we figured out to create subclasses using the following pattern:

'part of' some (length and ('inheres in' some BONE))

length and ('inheres in' some ('anatomical line' that 'follows axis' some 'AXIS' and ('inheres in' some BONE)))
