### ISSUE TITLE
supraoccipital crest length

### ISSUE THREAD

**Issue by helenamachado** [futres/fovt#89]
For new term requests, please provide the following information:

## Preferred term label

supraoccipital crest length

## Synonyms

(e.g., femur L)

## Parts of the term

1. anatomical feature: supraoccipital crest 
2. points on feature or axis of measurement: left-right axis of supraoccipital crest length
3. type of measurement: length

## Textual definition

The length of a supra occipital crest along the left-right axis.

subClassOf: 'part of' some (length and 'characteristic of' some 'supraoccipital crest'))

subClassOf: length and ('characteristic of' some ('anatomical line' that 'follows axis' some left-right axis and ('characteristic of' some supra occipital crest)))

## Reference

ISBN:9004086161, 9789004086166

## Attribution

https://orcid.org/0000-0001-8415-4848

**Comment by megbalk** [comment]
add what eisenmann calls the bone; import supraoccipital crest size (OBA:0003980

**Comment by megbalk** [comment]
assert subclass of supraoccipital bone size
