### ISSUE TITLE
New term for nose length

### ISSUE THREAD

**Issue by ramonawalls** [futres/fovt#9]
I need a new term for nose lenght, but I think noses are different in different taxa.

Proposed definintion: A length that inheres in a nose.

But, what is a nose?

@emerykf @rbernor @kmeshida @DrPronghorn Please tell me what you think a nose is?

**Comment by emerykf** [comment]
a nose is as long as it can sniff

**Comment by kmeshida** [comment]
nostril

**Comment by rbernor** [comment]
length of midface appendage = nose length

**Comment by rbernor** [comment]
length of midface appendage = nose length

**Comment by DrPronghorn** [comment]
My dog has no nose.

How does it smell?

Awful!

**Comment by rbernor** [comment]
Edward: bathe him then

**Comment by DrPronghorn** [comment]
Q: Who can smell the evil that lurks in the hearts of men?

A: The Shadow's nose!

**Comment by ramonawalls** [comment]
This question also relates to issue #4

**Comment by DrPronghorn** [comment]
> This question also relates to issue #4

Ramona nose how it's related...
