### ISSUE TITLE
foramen magnum breadth

### ISSUE THREAD

**Issue by helenamachado** [futres/fovt#90]
For new term requests, please provide the following information:

## Preferred term label

foramen magnum breadth

## Synonyms

(e.g., femur L)

## Parts of the term

1. anatomical feature: Foramen Magnum
2. points on feature or axis of measurement: left-right axis
3. type of measurement: length

## Textual definition

The length of a foramen magnum along the left-right axis.

subClassOf: 'part of' some (length and 'characteristic of' some 'foramen magnum'))

subClassOf: length and ('characteristic of' some ('anatomical line' that 'follows axis' some left-right axis and ('characteristic of' some 'foramen magnum')))

## Reference
ISBN:9004086161, 9789004086166
ISBN:9780873659505

## Attribution

https://orcid.org/0000-0001-8415-4848

**Comment by megbalk** [comment]
add what eisenmann calls it; fix measured_in_taxon
