### ISSUE TITLE
foramen magnum height

### ISSUE THREAD

**Issue by helenamachado** [futres/fovt#91]
For new term requests, please provide the following information:

## Preferred term label

foramen magnum height

## Parts of the term

1. anatomical feature: foramen magnum
2. points on feature or axis of measurement: midsagittal plane
3. type of measurement: length

## Textual definition

The length of a foramen magnum along the midsagittal plane.

subClassOf: 'part of' some (length and 'characteristic of' some 'foramen magnum'))

subClassOf: length and ('characteristic of' some ('anatomical line' that 'follows axis' some midsagittal plane and ('characteristic of' some 'foramen magnum')))

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/fovt)

## Reference
ISBN:9004086161, 9789004086166
ISBN:9780873659505

## Attribution

https://orcid.org/0000-0001-8415-4848)

**Comment by megbalk** [comment]
add what eisenmann and von den driesch calls it
