### ISSUE TITLE
occipital breadth

### ISSUE THREAD

**Issue by helenamachado** [futres/fovt#92]
For new term requests, please provide the following information:

## Preferred term label

occipital breadth

## Parts of the term

1. anatomical feature: occipital region
2. points on feature or axis of measurement: 
3. type of measurement: length

## Textual definition

The length of a line from the temporal fossa on the left side of the skull to the temporal fossa on the right side of the skull of an occipital region.

SubClass Of

length
 and ('characteristic of' some 'occipital region')

length
 and ('characteristic of' some 
    (anatomical line
     and (connects some 'temporal fossa' and ('in left side of' some skull))
     and (connects some ' temporal fossa' and ('in right side of' some skull))))

## Reference
ISBN:9780873659505

## Attribution

https://orcid.org/0000-0001-8415-4848

**Comment by megbalk** [comment]
change to: the length between the temporal fossa on the left and right side of the occipital region of a skull.
add in what eisenmann and von den dreisch calls them
